//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankLoan_FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string LoanType { get; set; }
        public string Amount { get; set; }
    }
}
